import GlobalLayout from "@/layout/GlobalLayout";
import type { Metadata } from "next";
import {
  Cormorant_Garamond,
  EB_Garamond,
  Geist,
  Geist_Mono,
  Rubik,
} from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import AppContextProvider from "@/providers/AppProvider";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-cormorant",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-ebgaramond",
  weight: ["400", "500", "700"],
  display: "swap",
});

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  weight: ["300", "400", "500", "700", "800", "900"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Memoirs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${cormorant.variable} antialiased`}>
        <NextTopLoader color="#d1192e" />
        {/* <Header /> */}
        <AppContextProvider>
          <GlobalLayout>{children}</GlobalLayout>
        </AppContextProvider>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
